spring.application.name=realestate
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=realestate

spring.data.mongodb.auto-create-index=true

jwt.secret=${JWT_SECRET:94a08da1fecbb6e8b46990538c7b50b294a08da1fecbb6e8b46990538c7b50b2}
jwt.expirationMs=86400000

cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

