package com.rems.realestate.model;

public enum PropertyStatus {
    AVAILABLE,
    PENDING,
    APPROVED,
    FLAGGED,
    REJECTED,
    SOLD,
    RENTED,
    SALE_IN_PROGRESS,
    RENT_IN_PROGRESS,
    PENDING_BUYER_CONFIRMATION,
    PENDING_OWNER_CONFIRMATION,
    PENDING_TENANT_CONFIRMATION
}
